### Subir una imagen de producto
POST http://localhost:4000/upload
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; name="product"; filename="test-image.jpg"
Content-Type: image/jpeg

< /home/rene/Documentos/noveno/ProyectoServicio/frontend/src/Components/Assets/logo.png
--MyBoundary--
### Añadir un nuevo producto
POST http://localhost:4000/addproduct
Content-Type: application/json

{
    "name": "Artesania",
    "category": "kid",
    "new_price": 10,
    "old_price": 8,
    "image": "url_de_la_imagen.jpg"
}

### Eliminar un producto
POST http://localhost:4000/removeproduct
Content-Type: application/json

{
    "id": 2,
    "name": "product 123"
}

### Eliminar un producto
GET http://localhost:4000/allproducts
Content-Type: application/json

### Crear Usuario
POST http://localhost:4000/signup
Content-Type: application/json

{
    "username": "PruebaRene",
    "password": "123",
    "email": "user@gmail.com"
}

### Iniciar sesion
POST http://localhost:4000/login
Content-Type: application/json

{
    "email": "user@gmail.com",
    "password": "123"
}